#!/bin/bash
set -e

PROFILE_BASE=/nix/var/nix/profiles/per-user/root
PROFILE=$PROFILE_BASE/packet-broker
REPO_GIT="https://github.com//alexandergall/packet-broker-nixpkgs"
REPO_API="https://api.github.com/repos/alexandergall/packet-broker-nixpkgs"

PATH=/nix/var/nix/profiles/default/bin:@PATH@
NIX_PATH=

self=$(basename $0)

usage () {
    echo "usage: $self OPTIONS
       Available options:
         --list-installed
         --list-available
         --switch-to-generation GENERATION
         --install-release RELEASE
         --install-git COMMIT
         --uninstall-generation GENERATION
         --activate-current
         --deactivate-current
         --cleanup
         --help"
    exit 0
}

opts=$(getopt -l list-installed \
              -l list-available \
              -l switch-to-generation: \
              -l install-release: \
              -l install-git: \
              -l uninstall-generation: \
              -l activate-current \
              -l deactivate-current \
              -l cleanup \
              -l help \
              -o "" \
              -n $self \
              -- "$@")
[ $? -eq 0 ] || usage
[ $# -eq 0 ] && usage
eval set -- $opts

while [ $# -gt 0 ]; do
    case "$1" in
        --list-available)
            list_available=1
            shift
            ;;
        --list-installed)
            list_installed=1
            shift
            ;;
        --switch-to-generation)
            switch_to_generation=$2
            shift 2
            ;;
        --uninstall-generation)
            uninstall_generation=$2
            shift 2
            ;;
        --install-release)
            install_release=$2
            shift 2
            ;;
        --install-git)
            install_git=$2
            shift 2
            ;;
        --activate-current)
            activate=1
            shift
            ;;
        --deactivate-current)
            deactivate=1
            shift
            ;;
        --cleanup)
            cleanup=1
            shift
            ;;
        --help)
            usage
            ;;
        *)
            break
            ;;
    esac
done
[ $# -gt 1 ] && usage

declare -A gens gens_by_id install_dates installed_releases available_releases
declare -A slices

gen_from_path () {
    echo $1 | sed -e 's/.*-\([0-9]*\)-link$/\1/'
}

for path in $PROFILE-*-link; do
    [ -h $path ] || continue
    slice=$(cat $path/slice)
    id=$(cat $path/version):$slice
    gen=$(gen_from_path $path)
    if [ -n "${gens_by_id[$id]}" ]; then
        echo "Generation $gen is a duplicate of ${gens_by_id[$id]}, ignoring"
    else
        gens[$gen]=$id
        gens_by_id[$id]=$gen
        install_dates[$gen]=$(stat -c "%z" $path)
        slices[$gen]=$slice

        read version gitTag rest < <(echo $id | tr ':' ' ')
        if [ "release-$version" == "$gitTag" ]; then
            installed_releases[$version]="${installed_releases[$version]} $gen"
        fi
    fi
done
current_gen=$(gen_from_path $(readlink $PROFILE))
kernel_release=$(uname -r)

check_root () {
    [ $(id -u) == 0 ] && return
    echo "Please run this command as root"
    exit 1
}

### Activate the current profile
SYSTEMD_DIR=/etc/systemd/system
CONFIG_DIR=/etc/packet-broker
CONFIG=$CONFIG_DIR/config.json
SCHEMA=$CONFIG_DIR/schema.json
SNMP_CONFIG_DIR=/etc/snmp
SNMPD_CONFIG=$SNMP_CONFIG_DIR/snmpd.conf
IFINDEX=$SNMP_CONFIG_DIR/ifindex
SNMP_STATE_DIR=/var/lib/snmp
INTERFACE_CONFIG=$SNMP_STATE_DIR/interface.conf
SHELL_PROFILE=/etc/profile.d/packet-broker.sh
activate () {
    check_root
    echo "Enabling services"
    for service in $PROFILE$SYSTEMD_DIR/*.service; do
        ln -fs $service $SYSTEMD_DIR
        systemctl enable $(basename $service)
    done
    systemctl daemon-reload
    for dir in $CONFIG_DIR $SNMP_CONFIG_DIR $SNMP_STATE_DIR; do
        [ -d $dir ] || mkdir -p $dir
    done
    for file in $SCHEMA $IFINDEX $INTERFACE_CONFIG; do
        ## For some weird reason, the Snabb SNMP agent barfs
        ## when doing a stat() on the ifindex file in the Nix
        ## store. So, instead of linking to the file, we copy
        ## it.  Need to figure what exactly the problem is.
        cp $PROFILE$file $file
    done
    for config in $CONFIG $SNMPD_CONFIG; do
        [ -e $config ] || cp $PROFILE$config $config
    done
    if [ ! -e $SHELL_PROFILE ]; then
        echo PATH=$PROFILE/bin:\$PATH >$SHELL_PROFILE
    fi
    echo "Starting services"
    systemctl start packet-broker
}

### Deactivate the current profile
deactivate () {
    check_root
    echo "Stopping services"
    systemctl stop packet-broker
    echo "Disabling services"
    for service in $PROFILE/$SYSTEMD_DIR/*.service; do
        systemctl disable $(basename $service)
    done
}

list_installed () {
    echo "Generation Current Release Git Tag      KernelID       Kernel Release            Install date"
    echo "-------------------------------------------------------------------------------------------------------------------"
    for gen in $(printf '%s\n' "${!gens[@]}" | sort -n); do
        read version gitTag kernelID kernelRelease < <(echo ${gens[$gen]} | tr ':' ' ')
        is_current=' '
        [ $gen -eq $current_gen ] && is_current='*'
        printf "%10d $is_current       %-7s %-12s %-14s %-25s %s\n" $gen $version $gitTag $kernelID $kernelRelease "${install_dates[$gen]}"
    done
}

get_available_releases () {
    echo "Checking for release tags of $REPO_GIT"
    for tag in $(curl $REPO_API/tags 2>/dev/null| jq '.[].name'); do
        gitTag=$(echo $tag | sed -e 's/"//g')
        [[ $gitTag =~ ^release-.*$ ]] || continue
        version=$(echo $gitTag | cut -d- -f2)
        available_releases[$version]=$gitTag
    done
}

list_available () {
    get_available_releases
    echo
    echo "Version  Status"
    echo "-----------------------------------------------"
    for version in $(printf '%s\n' "${!available_releases[@]}" | sort); do
        printf "%8s  " $version
        if [ -n "${installed_releases[$version]}" ]; then
            printf 'Installed in generaton(s) %s\n'\
                   $(echo "${installed_releases[$version]}" | sed -e 's/^ //;s/ /, /g')
        else
            echo "Not installed"
        fi
    done
}

switch_to_generation () {
    check_root
    if [ -z "${gens[$switch_to_generation]}" ]; then
        echo "Generation $switch_to_generation does not exist"
        exit 1
    fi
    if [ $switch_to_generation -eq $current_gen ]; then
        echo "Generation $switch_to_generation is already the current version"
        exit 1
    fi
    echo "Deactivating current instance"
    deactivate
    if [ "${slices[$switch_to_generation]}" != "${slices[$current_gen]}" ]; then
        ## Kernel has changed, unload modules and let them
        ## be reloaded by the wrapper during activation.
        echo "New generation uses a different kernel (${slices[$switch_to_generation]})"
        for module in $(lsmod | awk '{print $1}'); do
            if [[ $module =~ bf_ ]]; then
                echo "Unloading module $module"
                rmmod $module
            fi
        done
    fi
    nix-env -p $PROFILE --switch-generation $switch_to_generation
    ## The new release may have a different activation procedure.  Use
    ## its native release-manager to perform the activation.
    echo "Activating new instance"
    $PROFILE/bin/release-manager --activate
}

_check_installed () {
    gitTag=$1
    version=$(echo $gitTag | cut -d- -f2)
    kernel_id=$(nix eval --raw \
                    '(with import ./. { gitTag = "'$gitTag'"; kernelRelease = "'$kernel_release'"; };
                     install.moduleWrapper.modules.kernelID)')
    id=$version:$gitTag:$kernel_id:$kernel_release
    gen=${gens_by_id[$id]}
    if [ -n "$gen" ]; then
        echo "Release $version (Id: $id) is already installed as generation $gen"
        exit 1
    fi
}

_install () {
    gitTag=$1
    nix-env -f . -p $PROFILE -r -i -A install --argstr gitTag $gitTag --argstr kernelRelease $kernel_release
    new_gen=$(gen_from_path $(readlink $PROFILE))
    ## nix-env has automatically switched to the new
    ## generation, revert back
    nix-env -p $PROFILE --switch-generation $current_gen 2>/dev/null

    echo -n "Use \"release-manager --switch-to-generation $new_gen\" to "
    echo    "switch to the new release"
}

install_git () {
    check_root
    tmp=$(mktemp -d)
    pushd $tmp >/dev/null
    echo "Fetching $install_git"
    git init
    git remote add origin $REPO_GIT
    git fetch origin
    git reset --hard $install_git

    gitTag=$(git describe --always)
    _check_installed $gitTag
    _install $gitTag

    popd >/dev/null
    rm -rf $tmp
}

install_release () {
    check_root
    get_available_releases
    gitTag=${available_releases[$install_release]}
    if [ -z "$gitTag" ]; then
        echo "Release $install_release does not exist"
        exit 1
    fi
    tarball=$REPO_GIT/archive/$gitTag.tar.gz
    echo "Fetching package release tarball $tarball"
    tmp=$(mktemp -d)
    pushd $tmp >/dev/null
    curl -L -O $tarball 2>/dev/null
    tar xf release-* --strip-component 1

    _check_installed $gitTag
    _install $gitTag

    popd >/dev/null
    rm -rf $tmp
}

uninstall_generation () {
    check_root
    if [ -z "${gens[$uninstall_generation]}" ]; then
        echo "Generation $uninstall_generation does not exist"
        exit 1
    fi
    if [ $uninstall_generation -eq $current_gen ]; then
        echo "Can't uninstall current generation"
        exit 1
    fi
    nix-env -p $PROFILE --delete-generations $uninstall_generation
}

cleanup () {
    nix-collect-garbage
}

[ -n "$list_installed" ] && list_installed
[ -n "$list_available" ] && list_available
[ -n "$switch_to_generation" ] && switch_to_generation
[ -n "$install_release" ] && install_release
[ -n "$install_git" ] && install_git
[ -n "$uninstall_generation" ] && uninstall_generation
[ -n "$activate" ] && activate
[ -n "$deactivate" ] && deactivate
[ -n "$cleanup" ] && cleanup
