#!/bin/bash
set -e

PROFILE_BASE=/nix/var/nix/profiles/per-user/root
PROFILE=$PROFILE_BASE/packet-broker
REPO_GIT="https://github.com//alexandergall/packet-broker-nixpkgs"
REPO_API="https://api.github.com/repos/alexandergall/packet-broker-nixpkgs"

PATH=/nix/var/nix/profiles/default/bin:@PATH@
NIX_PATH=

self=$(basename $0)

usage () {
    echo "usage: $self OPTIONS
       Available options:
         --list-installed
         --list-available
         --switch-to-generation GENERATION
         --install-release RELEASE
         --install-git COMMIT
         --uninstall-generation GENERATION
         --activate-current
         --deactivate-current
         --cleanup
         --help"
    exit 0
}

opts=$(getopt -l list-installed \
              -l list-available \
              -l switch-to-generation: \
              -l install-release: \
	      -l install-git: \
              -l uninstall-generation: \
              -l activate-current \
              -l deactivate-current \
              -l cleanup \
              -l help \
              -o "" \
              -n $self \
              -- "$@")
[ $? -eq 0 ] || usage
[ $# -eq 0 ] && usage
eval set -- $opts

while [ $# -gt 0 ]; do
    case "$1" in
        --list-available)
            list_available=1
            shift
            ;;
        --list-installed)
            list_installed=1
            shift
            ;;
        --switch-to-generation)
            switch_to_generation=$2
            shift 2
            ;;
        --uninstall-generation)
            uninstall_generation=$2
            shift 2
            ;;
        --install-release)
            install_release=$2
            shift 2
            ;;
        --install-git)
            install_git=$2
            shift 2
            ;;
        --activate-current)
            activate=1
            shift
            ;;
        --deactivate-current)
            deactivate=1
            shift
            ;;
        --cleanup)
            cleanup=1
            shift
            ;;
        --help)
            usage
            ;;
        *)
            break
            ;;
    esac
done
[ $# -gt 1 ] && usage

declare -A gens gens_by_path gens_by_id versions_by_id install_date available_releases

for path in $PROFILE-*-link; do
    [ -h $path ] || continue
    short_path=$(basename $path)
    gen=$(echo $short_path | sed -e 's/.*-\([0-9]*\)-link$/\1/')
    gens[$gen]=$short_path
    gens_by_path[$short_path]=$gen
    id=$(cat $path/version.id)
    gens_by_id[$id]=$gen
    versions_by_id[$id]=$(cat $path/version)
    install_date[$gen]=$(stat -c "%z" $path)
done
current_path=$(readlink $PROFILE)
current_gen=${gens_by_path[$current_path]}

check_root () {
    [ $(id -u) == 0 ] && return
    echo "Please run this command as root"
    exit 1
}

### Activate the current profile
SYSTEMD_DIR=/etc/systemd/system
CONFIG_DIR=/etc/packet-broker
CONFIG=$CONFIG_DIR/config.json
SCHEMA=$CONFIG_DIR/schema.json
SNMP_CONFIG_DIR=/etc/snmp
SNMPD_CONFIG=$SNMP_CONFIG_DIR/snmpd.conf
IFINDEX=$SNMP_CONFIG_DIR/ifindex
SNMP_STATE_DIR=/var/lib/snmp
INTERFACE_CONFIG=$SNMP_STATE_DIR/interface.conf
SHELL_PROFILE=/etc/profile.d/packet-broker.sh
activate () {
    check_root
    echo "Enabling services"
    for service in $PROFILE$SYSTEMD_DIR/*.service; do
        ln -fs $service $SYSTEMD_DIR
        systemctl enable $(basename $service)
    done
    systemctl daemon-reload
    for dir in $CONFIG_DIR $SNMP_CONFIG_DIR $SNMP_STATE_DIR; do
	[ -d $dir ] || mkdir -p $dir
    done
    for file in $SCHEMA $IFINDEX $INTERFACE_CONFIG; do
	## For some weird reason, the Snabb SNMP agent barfs
	## when doing a stat() on the ifindex file in the Nix
	## store. So, instead of linking to the file, we copy
	## it.  Need to figure what exactly the problem is.
	cp $PROFILE$file $file
    done
    for config in $CONFIG $SNMPD_CONFIG; do
	[ -e $config ] || cp $PROFILE$config $config
    done
    if [ ! -e $SHELL_PROFILE ]; then
        echo PATH=$PROFILE/bin:\$PATH >$SHELL_PROFILE
    fi
    echo "Starting services"
    systemctl start packet-broker
}

### Deactivate the current profile
deactivate () {
    check_root
    echo "Stopping services"
    systemctl stop packet-broker
    echo "Disabling services"
    for service in $PROFILE/$SYSTEMD_DIR/*.service; do
        systemctl disable $(basename $service)
    done
}

list_installed () {
    echo "Generation Current Release Install date                        Id"
    echo "------------------------------------------------------------------------"
    for gen in $(printf '%s\n' "${!gens[@]}" | sort -n); do
	path=$PROFILE_BASE/${gens[$gen]}
        release=$(cat $path/version)
	id=$(cat $path/version.id)
        current=' '
        [ $gen -eq $current_gen ] && current='*'
        printf "%10d $current       %-7s %s %s\n" $gen $release "${install_date[$gen]}" $id
    done
}

get_available_releases () {
    echo "Checking for release tags of $REPO_GIT"
    for tag in $(curl $REPO_API/tags 2>/dev/null| jq '.[].name'); do
        tag=$(echo $tag | sed -e 's/"//g')
        [[ $tag =~ ^release-.*$ ]] || continue
        release=$(echo $tag | cut -d- -f2)
        available_releases[$release]=$tag
    done
}

list_available () {
    get_available_releases
    echo
    echo "Release  Status"
    echo "-----------------------------------------------"
    for release in $(printf '%s\n' "${!available_releases[@]}" | sort); do
        printf "%8s  " $release
	id=${available_releases[$release]}
        gen="${gens_by_id[$id]}"
        if [ -n "$gen" ]; then
            echo "Locally installed as generation $gen"
        else
            echo "Not installed locally"
        fi
    done
}

switch_to_generation () {
    check_root
    if [ -z "${gens[$switch_to_generation]}" ]; then
        echo "Generation $switch_to_generation does not exist"
        exit 1
    fi
    if [ $switch_to_generation -eq $current_gen ]; then
        echo "Generation $switch_to_generation is already the current version"
        exit 1
    fi
    echo "Deactivating current instance"
    deactivate
    nix-env -p $PROFILE --switch-generation $switch_to_generation
    ## The new release may have a different activation procedure.  Use
    ## its native release-manager to perform the activation.
    echo "Activating new instance"
    $PROFILE/bin/release-manager --activate
}

_check_installed () {
    local gen
    gen=${gens_by_id[$1]}
    if [ -n "$gen" ]; then
	version=${versions_by_id[$1]}
        echo "Release $version (Id: $1) is already installed as generation $gen"
        exit 1
    fi
}

_install () {
    nix-env -f . -p $PROFILE -r -i -A install --argstr gitTag $1
    new_gen=$(readlink $PROFILE | sed -e 's/.*-\([0-9]*\)-link$/\1/')
    ## nix-env has automatically switched to the new
    ## generation, revert back
    nix-env -p $PROFILE --switch-generation $current_gen 2>/dev/null

    echo -n "Use \"release-manager --switch-to-generation $new_gen\" to "
    echo    "switch to the new release"
}

install_git () {
    check_root
    tmp=$(mktemp -d)
    pushd $tmp >/dev/null
    echo "Fetching $install_git"
    git init
    git remote add origin $REPO_GIT
    git fetch origin
    git reset --hard $install_git

    tag=$(git describe --always)
    _check_installed $tag
    _install $tag

    popd >/dev/null
    rm -rf $tmp
}

install_release () {
    check_root
    get_available_releases
    tag=${available_releases[$install_release]}
    if [ -z "$tag" ]; then
        echo "Release $install_release does not exist"
        exit 1
    fi
    _check_installed $tag
    tarball=$REPO_GIT/archive/$tag.tar.gz
    echo "Fetching package release tarball $tarball"
    tmp=$(mktemp -d)
    pushd $tmp >/dev/null
    curl -L -O $tarball 2>/dev/null
    tar xf release-* --strip-component 1

    _install $tag

    popd >/dev/null
    rm -rf $tmp
}

uninstall_generation () {
    check_root
    if [ -z "${gens[$uninstall_generation]}" ]; then
        echo "Generation $uninstall_generation does not exist"
        exit 1
    fi
    if [ $uninstall_generation -eq $current_gen ]; then
        echo "Can't uninstall current generation"
        exit 1
    fi
    nix-env -p $PROFILE --delete-generations $gen
}

cleanup () {
    nix-collect-garbage
}

[ -n "$list_installed" ] && list_installed
[ -n "$list_available" ] && list_available
[ -n "$switch_to_generation" ] && switch_to_generation
[ -n "$install_release" ] && install_release
[ -n "$install_git" ] && install_git
[ -n "$uninstall_generation" ] && uninstall_generation
[ -n "$activate" ] && activate
[ -n "$deactivate" ] && deactivate
[ -n "$cleanup" ] && cleanup
